In [1]:
import numpy as np


In [2]:
# axes in multi-dimentional arrays
"""
1d >> 1 axis(axis 0)

2D >> 2axes{
(0 for row )>>> vertical operations in collum vise
(1 for collum ) horijental operations in row vise
"""

# 3D  array is a  combination of 2d arrays >> 3exes
"""
{
(0 for depth/layers)
(1 for row in each layer)
(3 for collum in each layers)
}
"""
# we define the 3d array with (layer no,row no,collum no)
#example 
"""
arr3d[2,3,2]

thats mean...
1...select the 3rd 2d meetrix means 2no layer
2...select the row3
3... select the collum2
"""


'\narr3d[2,3,2]\n\nthats mean...\n1...select the 3rd 2d meetrix means 2no layer\n2...select the row3\n3... select the collum2\n'

In [5]:
arr2d=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr2d)

print(np.sum(arr2d))

sum_of_collum=np.sum(arr2d,axis=0)
print(sum_of_collum)

sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows)

# exes the 2 and 4
print(arr2d[0:2,1:2])

[[1 2 3]
 [3 4 5]
 [5 6 7]]
36
[ 9 12 15]
[ 6 12 18]
[[2]
 [4]]


In [18]:
# 3d array create
arr3d=np.array([[[1,2],[2,3],[3,4]] ,[[5,6],[3,7],[2,4]]]) #it is a 2*3*2
print(arr3d,arr3d.shape)

# indexing and slcysing
print(arr3d[0,0,0])
print(arr3d[1,0,0])
print(arr3d[1,1,1])

print(arr3d[0:2,0,0:2]) #first row form both layers
print(arr3d[0:2,0:3,0]) #first collum form both layers

# value changing
arr3d[0:2,0,0:2]=90
print(arr3d)

[[[1 2]
  [2 3]
  [3 4]]

 [[5 6]
  [3 7]
  [2 4]]] (2, 3, 2)
1
5
7
[[1 2]
 [5 6]]
[[1 2 3]
 [5 3 2]]
[[[90 90]
  [ 2  3]
  [ 3  4]]

 [[90 90]
  [ 3  7]
  [ 2  4]]]
