Normalization- normalizing an array means transforming its valus so they fill into a specific scale of range

In [3]:
import numpy as np

std normalization formula..

(arr-mean)/std dev

{[(VAL_i - mean)^2]/N }^1/2

In [11]:
arr=np.array([[1,2],[3,4]])

mean=np.mean(arr)
std_dev= np.std(arr)

print(mean)
print(std_dev)

nm_arr= (arr-mean)/std_dev
print(nm_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [36]:
# mathematical function

arr=np.array([1,2,3,4,5])

# agrication function

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.median(arr))
print(np.argmax(arr))



15
120
1
5
3.0
1.4142135623730951
2.0
0
3.0
4


In [37]:
arr=np.array([1,2,3,4,5])

# power functions

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]


In [38]:
arr=np.array([1,2,3,4,5])

# log and expotential function

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [43]:
arr=np.array([1,2,3,4,5])
# rounding function

print(np.round(4.0))
print(np.floor(3.5))
print(np.ceil(2))
print(np.trunc(arr))


4.0
3.0
2
[1 2 3 4 5]


In [45]:
arr=np.array([1,2,3,4,7,6,4,6,5,-6,-5])

# extra functions

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))


[-6 -5  1  2  3  4  5  6  7]
[-6 -5  1  2  3  4  4  5  6  6  7]
[1 2 3 4 7 6 4 6 5 6 5]
