In [1]:
import numpy as np

In [5]:
# properties of np

arr = np.array([[3,4,6],[3,4,5],[6,7,8]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

# Type casting method

# 1..  scretch se krne ke lie [dtype property use]
# ( arr1=np.zeros((2,3),dtype="int64"))

# 2.. old array se new array create kr rhe he to
# as type function

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[3. 4. 6.]
 [3. 4. 5.]
 [6. 7. 8.]] float64
