In [1]:
import numpy as np

In [14]:
# create in build in function

# for zero metrix
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

# for one  metrix
arr2=np.ones((2,3),dtype="int64")
print(arr2,arr2.shape)    

# for fixed value  metrix like 100 in every row and cllum
arr3=np.full((3,4),100,dtype="int64")
print(arr3,arr3.shape)

# for identity  metrix only digonal values are 1
arr4=np.eye((3),dtype="int64")
print(arr4,arr4.shape)

# for range values print metrix
arr5=np.arange(1,11)
print(arr5,arr5.shape)

# for range in even metrix
arr6=np.arange(1,11,2)
print(arr6,arr6.shape)

# for range but we define how values in the metrix (4 values)
arr7=np.linspace(1,100,4)
print(arr7,arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)
