In [1]:
import numpy as np

In [5]:
# cresting numpy array from list 
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

arr2=np.array([3,4,5,6,"prime",'a'])
print(arr2,type(arr2))

# 2D_array metrix
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3,type(arr3),arr3.shape)


[1 2 3 4 5] <class 'numpy.ndarray'>
['3' '4' '5' '6' 'prime' 'a'] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)
