In [2]:
import numpy as np

In [7]:
# OPERATIONS On ARRAY

# 1st operation is reshaping that ocnvert the row to collim and collum to row
arr= np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

# 2nd is flatend array that convert the array in 1D
flattend=arr.flatten() #2D to 1D
print(flattend,flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [16]:
# indexing

arr2= np.array([[1,2,3],[4,5,6]])
print(arr2[0][1]) #2  ,first row 2nd collum
print(arr2[1][2]) #6   second row 3rd collum

#fancy inexing
arr= np.array([1,2,3,4,5,6])

idx=[0,1,4]
print(arr[idx])

# boolean indexing
arr3= np.array([1,2,3,4,5,6])
print(arr3[arr>2]) 
print(arr3[arr<2]) 
print(arr3[arr==0]) 
print(arr3[arr!=0]) 

# sliceying operation(alag se mem use nhi krti list ki trh)
# [start,end,step]

print(arr[1:3]) 
print(arr[:4]) #auto start with 0
print(arr[0:]) #auto end with  n index


2
6
[1 2 5]
[3 4 5 6]
[1]
[]
[1 2 3 4 5 6]
[2 3]
[1 2 3 4]
[1 2 3 4 5 6]


In [25]:
# copy vs view 

num=[2,3,4,5,6]
sub_list = num[1:4]
print(sub_list)
sub_list[0]=20

print(num)
print(sub_list)


nums=np.array([2,3,4,5,6])
sub_arr = nums[1:4]
print(sub_arr)
sub_arr[0]=20

print(sub_arr)
print(nums) #[ 2 20  4  5  6] 
# changes in orignal array,not creating any copy
# if we need any copy of the araay we use the copy() function

nums=np.array([2,3,4,5,6])
sub_arr = nums[1:4].copy() #create a copy of the array
print(sub_arr)
sub_arr[0]=20

print(sub_arr)
print(nums) 
 


[3, 4, 5]
[2, 3, 4, 5, 6]
[20, 4, 5]
[3 4 5]
[20  4  5]
[ 2 20  4  5  6]
[3 4 5]
[20  4  5]
[2 3 4 5 6]
