In [2]:
import numpy as np

In [ ]:
# rules of broadcsting

""" When operating on two arrays,
NumPy compares their shapes element-wise. 
It starts with the trailing (i.e. rightmost) dimension and works its way left. """

# Two dimensions are compatible when
"""
# they are equal, or
# one of them is 1.
"""

# (2,3) (2,3) >>equal to
# (2,3) (1,3) >> one of them is one

"""
If these conditions are not met,
a ValueError: operands could not be broadcast together exception is thrown, 
indicating that the arrays have incompatible shapes."""

# Input arrays do not need to have the same number of dimensions. 
"""
The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions,
where the size of each dimension is the largest size of the corresponding dimension among the input arrays.
Note that missing dimensions are assumed to have size one.
"""

# For example, 
"""
    if you have a 256x256x3 array of RGB values, 
and you want to scale each color in the image by a different value,
you can multiply the image by a one-dimensional array with 3 values. 
Lining up the sizes of the trailing axes of these arrays according to the broadcast rules,
shows that they are compatible:"""

In [4]:
# vecterization 

arr= np.array([2,3,4,5,6])
arr2= np.array([5,6,4,6,3])

print(arr**2)
print(arr+arr2)

[ 4  9 16 25 36]
[ 7  9  8 11  9]


In [10]:
# broadcasting
# when we have a scaler value for operation with the vector thats time we use this concepts
# example  >>> ([2,3,4,1,4]+6)

arr= np.array([2,3,4,5,6])
arr2= np.array([[5,6,4,6,3],[3,4,6,3,7]])

print(arr+arr2) #arr is adding both 2d arrays
print(arr.shape,arr2.shape) #(5,) (2, 5)


# if the values are mismatch
"""
arr= np.array([[2,3,4,5,6],[3,4,5,2,1],[7,8,9,5,0]])  #(3,5)
arr2= np.array([[5,6,4,6,3],[3,4,6,3,7]]) #(2,5)
print(arr+arr2)

"""
# mismatch  with shapes (3,5) (2,5) 

# ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 


[[ 7  9  8 11  9]
 [ 5  7 10  8 13]]
(5,) (2, 5)


'\narr= np.array([[2,3,4,5,6],[3,4,5,2,1],[7,8,9,5,0]])  #(3,5)\narr2= np.array([[5,6,4,6,3],[3,4,6,3,7]]) #(2,5)\nprint(arr+arr2)\n\n'